from django.conf import settings

ADWARE_TEMPLATE_BASE_DIR = getattr(settings, 'ADWARE_TEMPLATE_BASE_DIR', 'ads')
ADWARE_MINIMUM_IMPRESSION_PERCENTAGE = getattr(settings, 'ADWARE_MINIMUM_IMPRESSION_PERCENTAGE', 30)
